//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDutch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDutch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryManagementSystem.ResourceDutch", typeof(ResourceDutch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung! Annäherung an die Entladung.
        /// </summary>
        internal static string ApproachingDischarge {
            get {
                return ResourceManager.GetString("ApproachingDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung! Annäherung an den Gipfel.
        /// </summary>
        internal static string ApproachingPeak {
            get {
                return ResourceManager.GetString("ApproachingPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladungsbruch - hoch.
        /// </summary>
        internal static string ChargeRateBreachHigh {
            get {
                return ResourceManager.GetString("ChargeRateBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladungsbruch - Niedrig.
        /// </summary>
        internal static string ChargeRateBreachLow {
            get {
                return ResourceManager.GetString("ChargeRateBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Laderate liegt außerhalb des zulässigen Bereichs.
        /// </summary>
        internal static string ChargeRateOutOfRange {
            get {
                return ResourceManager.GetString("ChargeRateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an den Spitzenwert der Laderate.
        /// </summary>
        internal static string ChargeRateToleranceHigh {
            get {
                return ResourceManager.GetString("ChargeRateToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an niedrige Laderate.
        /// </summary>
        internal static string ChargeRateToleranceLow {
            get {
                return ResourceManager.GetString("ChargeRateToleranceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist hohe Verletzung!.
        /// </summary>
        internal static string IsHighBreach {
            get {
                return ResourceManager.GetString("IsHighBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist niedrige Verletzung!.
        /// </summary>
        internal static string IsLowBreach {
            get {
                return ResourceManager.GetString("IsLowBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist ungültig!.
        /// </summary>
        internal static string IsNotValid {
            get {
                return ResourceManager.GetString("IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstoß gegen den Ladezustand - hoch.
        /// </summary>
        internal static string StateOfChargeBreachHigh {
            get {
                return ResourceManager.GetString("StateOfChargeBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstoß gegen den Ladezustand - Niedrig.
        /// </summary>
        internal static string StateOfChargeBreachLow {
            get {
                return ResourceManager.GetString("StateOfChargeBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Chage-Status liegt außerhalb der Reichweite.
        /// </summary>
        internal static string StateOfChargeOutOfRange {
            get {
                return ResourceManager.GetString("StateOfChargeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an die Ladungsspitze.
        /// </summary>
        internal static string StateOfChargeToleranceHigh {
            get {
                return ResourceManager.GetString("StateOfChargeToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an die Entladung.
        /// </summary>
        internal static string StateOfChargeToleranceLow {
            get {
                return ResourceManager.GetString("StateOfChargeToleranceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Temperatur liegt außerhalb des Bereichs.
        /// </summary>
        internal static string TemperatueOutOfRange {
            get {
                return ResourceManager.GetString("TemperatueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperaturbruch - Hoch.
        /// </summary>
        internal static string TemperatureBreachHigh {
            get {
                return ResourceManager.GetString("TemperatureBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperaturbruch - Niedrig.
        /// </summary>
        internal static string TemperatureBreachLow {
            get {
                return ResourceManager.GetString("TemperatureBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an die Temperaturspitze.
        /// </summary>
        internal static string TemperatureToleranceHigh {
            get {
                return ResourceManager.GetString("TemperatureToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung!! Annäherung an niedrige Temperatur.
        /// </summary>
        internal static string TemperatureToleranceLow {
            get {
                return ResourceManager.GetString("TemperatureToleranceLow", resourceCulture);
            }
        }
    }
}
