//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryManagementSystem.ResourceEnglish", typeof(ResourceEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in Charge Rate - High.
        /// </summary>
        internal static string ChargeRateBreachHigh {
            get {
                return ResourceManager.GetString("ChargeRateBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in Charge Rate - Low.
        /// </summary>
        internal static string ChargeRateBreachLow {
            get {
                return ResourceManager.GetString("ChargeRateBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Rate is out of Range.
        /// </summary>
        internal static string ChargeRateOutOfRange {
            get {
                return ResourceManager.GetString("ChargeRateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching charge rate peak.
        /// </summary>
        internal static string ChargeRateToleranceHigh {
            get {
                return ResourceManager.GetString("ChargeRateToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching low charge rate.
        /// </summary>
        internal static string ChargeRateToleranceLow {
            get {
                return ResourceManager.GetString("ChargeRateToleranceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in State of Charge - High.
        /// </summary>
        internal static string StateOfChargeBreachHigh {
            get {
                return ResourceManager.GetString("StateOfChargeBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in State of Charge - Low.
        /// </summary>
        internal static string StateOfChargeBreachLow {
            get {
                return ResourceManager.GetString("StateOfChargeBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of chage is out of Range.
        /// </summary>
        internal static string StateOfChargeOutOfRange {
            get {
                return ResourceManager.GetString("StateOfChargeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching charge peak.
        /// </summary>
        internal static string StateOfChargeToleranceHigh {
            get {
                return ResourceManager.GetString("StateOfChargeToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching discharge.
        /// </summary>
        internal static string StateOfChargeToleranceLow {
            get {
                return ResourceManager.GetString("StateOfChargeToleranceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is Out of Range.
        /// </summary>
        internal static string TemperatueOutOfRange {
            get {
                return ResourceManager.GetString("TemperatueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in temperature - High.
        /// </summary>
        internal static string TemperatureBreachHigh {
            get {
                return ResourceManager.GetString("TemperatureBreachHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach in temperature - Low.
        /// </summary>
        internal static string TemperatureBreachLow {
            get {
                return ResourceManager.GetString("TemperatureBreachLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching temperature peak.
        /// </summary>
        internal static string TemperatureToleranceHigh {
            get {
                return ResourceManager.GetString("TemperatureToleranceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!! Approaching low temperature.
        /// </summary>
        internal static string TemperatureToleranceLow {
            get {
                return ResourceManager.GetString("TemperatureToleranceLow", resourceCulture);
            }
        }
    }
}
